---
- name: Include Operating System specific vars
  include_vars: '{{ ansible_distribution }}.yml'

- name: Install editor packages
  become: true
  package:
    name: '{{ editor_packages }}'

- name: Ensure plugin path exists
  file:
    path: ' ~/.vim/pack/plugins/start'
    state: directory
    recurse: true

- name: Install plugins
  git:
    repo: 'https://github.com/{{ item }}.git'
    dest: '~/.vim/pack/plugins/start/{{ item | basename }}'
  loop:
    - Yggdroot/indentLine
    - airblade/vim-gitgutter
    - dense-analysis/ale
    - kien/ctrlp.vim
    - mileszs/ack.vim
    - cohama/lexima.vim
    - tpope/vim-commentary
