---
- hosts: localhost
  tasks:
    - name: Include packages role
      include_role:
        name: packages

    - name: Include config role
      include_role:
        name: config

    - name: Include services role
      include_role:
        name: services

    - name: Include terminal
      include_role:
        name: terminal
      vars:
        terminal: '{{ terminal }}'
