---
- hosts: localhost
  tasks:
    - name: Assert required variables are passed
      assert:
        that:
          - windowmanager is defined and windowmanager != ''
          - terminal is defined and terminal != ''

    - name: Include packages role
      include_role:
        name: packages

    - name: Include config role
      include_role:
        name: config

    - name: Include services role
      include_role:
        name: services

    - name: Include windownmanager
      include_role:
        name: windowmanager
      vars:
        windowmanager: '{{ windowmanager }}'

    - name: Include terminal
      include_role:
        name: terminal
      vars:
        terminal: '{{ terminal }}'
