---
- name: Include Operating System specific vars
  include_vars: '{{ ansible_distribution }}.yml'

- name: Start and enable system services
  become: true
  systemd:
    name: '{{ system_services }}'
    state: started
    enabled: true

- name: Start and enable user services
  systemd:
    name: '{{ user_services }}'
    state: started
    enabled: true
    scope: user
