---
- name: Include Operating System specific vars
  include_vars: '{{ ansible_distribution }}.yml'

- name: Start and enable system services
  become: true
  systemd:
    name: '{{ item }}'
    state: started
    enabled: true
  loop: '{{ system_services }}'

- name: Start and enable user services
  systemd:
    name: '{{ item }}'
    state: started
    enabled: true
    scope: user
  loop: '{{ user_services }}'
