" Global configuration
"

set backspace=indent,eol,start
set colorcolumn=+1
set cursorline
set encoding=utf-8
set laststatus=2
set list
set listchars=tab:>-,trail:↞,nbsp:«
set nocompatible
set number
set ruler

set noswapfile
set nobackup
set nowritebackup

set autoread
set autoindent

color elflord
syntax on
filetype plugin indent on

" ColorColumn configuration
highlight ColorColumn ctermbg=0

" SignColumn configuration
highlight clear SignColumn
highlight SignColumn guibg=NONE

" YAML
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab smarttab

" List of plugins to install in ~/.vim/pack/git-plugins/start
" PLUGIN-START
" Yggdroot/indentLine.git
" airblade/vim-gitgutter.git
" dense-analysis/ale.git
" kien/ctrlp.vim.git
" mileszs/ack.vim.git
" cohama/lexima.vim

" Linter - dense-analysis/ale.git
let g:ale_set_signs = 1
let g:ale_sign_error = ' ✘'
let g:ale_sign_warning = ' ⚠'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
highlight ALEErrorSign ctermbg=NONE guibg=NONE ctermfg=red guifg=red
highlight ALEWarningSign ctermbg=NONE guibg=NONE ctermfg=3* guifg=yellow

" indentLine - Yggdroot/indentLine.git
let g:indentLine_char = '⠂'
let g:indentLine_color_term = 1

" gitgutter - airblade/vim-gitgutter.git
let g:gitgutter_override_sign_column_highlight = 0
highlight GitGutterAdd  ctermbg=NONE guibg=NONE ctermfg=2* guifg=green
highlight GitGutterChange ctermbg=NONE guibg=NONE ctermfg=3* guifg=yellow
highlight GitGutterDelete ctermbg=NONE guibg=NONE ctermfg=red guifg=red
highlight GitGutterChangeDelete  ctermbg=NONE guibg=NONE ctermfg=red guifg=red
